version: "3.7"
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: nirmadb
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    ports:
      - 27017:27017
    networks:
      - nirma-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - nirma-network

  geoservice:
    image: tkremen/nirma-geoservice:1.0
    container_name: geoservice
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      WAIT_HOSTS: mongodb:27017,rabbitmq:5672
      WAIT_TIMEOUT: 60
      MONGO_DB: nirmadb
      MONGO_URL: mongodb://mongodb:27017
      MONGO_USERNAME: user
      MONGO_PASSWORD: password
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin
    networks:
      - nirma-network

networks:
  nirma-network:
    name: custom-nirma-network