version: "3.7"
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: nirmadb
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./mongodb/data/db/:/data/db/
      - ./mongodb/data/log/:/var/log/mongodb/
    ports:
      - 27017:27017
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  geoservice:
    image: tkremen/nirma-geoservice:1.3
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: geoservice
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      API_URL: http://host.docker.internal:8080
      WAIT_HOSTS: mongodb:27017,rabbitmq:5672
      WAIT_TIMEOUT: 60
      MONGO_DB: nirmadb
      MONGO_URL: mongodb://mongodb:27017
      MONGO_USERNAME: user
      MONGO_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: admin

  nirma-ui:
    image: tkremen/nirma-front:1.2
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    container_name: nirma-ui
    environment:
      API_URL: http://host.docker.internal:8080
      WAIT_HOSTS: geoservice:8080,
      WAIT_TIMEOUT: 120
    ports:
      - 8081:80