server:
  servlet:
    contextPath: /
  port: 8080
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/geoservice.p12
#    key-store-password: password
#    key-alias: geoservice
#    key-password: password
#    enabled: true

spring:
  jackson:
    date-format: org.nirma.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs
nirma:
  mongodb:
    uri: ${MONGO_URL}/${MONGO_DB}
    database: ${MONGO_DB}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    queue: featureQueue
    routingkey: nirma.featureQueue
    exchange: featureExchange